CREATE TABLE IF NOT EXISTS mpa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20)   NOT NULL,
    CONSTRAINT uc_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS film (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)   NOT NULL,
    releaseDate date    NOT NULL,
    duration integer    NOT NULL,
    mpa_id integer NOT NULL,
    description varchar(200)    NOT NULL,
    rate integer,
    CONSTRAINT fk_film_mpa_id FOREIGN KEY(mpa_id) REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100)   NOT NULL,
    login varchar(100)   NOT NULL,
    name varchar(100)   NOT NULL,
    birthday date,
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_login UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS film_like (
    film_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT fk_film_id FOREIGN KEY (film_id) REFERENCES film (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS genre (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    CONSTRAINT uc_genre_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id bigint NOT NULL,
    genre_id integer NOT NULL,
    CONSTRAINT fk_genre_film_id FOREIGN KEY (film_id) REFERENCES film (id),
    CONSTRAINT fk_genre_id FOREIGN KEY (genre_id) REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS friendship (
    user_id bigint NOT NULL,
    friend_id bigint NOT NULL,
    CONSTRAINT fc_friend_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fc_friend_friend_id FOREIGN KEY (friend_id) REFERENCES users (id)
);

